// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto.Persistence;

namespace Proyecto.Persistence.Migrations
{
    [DbContext(typeof(ProyectoContext))]
    [Migration("20190320194439_CrearTablasIniciales")]
    partial class CrearTablasIniciales
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proyecto.Core.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("Etiqueta");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<string>("Fondo");

                    b.Property<string>("Icono");

                    b.Property<string>("Nombre");

                    b.Property<string>("Url");

                    b.Property<string>("Ventana");

                    b.Property<bool>("Visible");

                    b.HasKey("Id");

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Indicadores",
                            Etiqueta = "Indicadores",
                            FechaCreacion = new DateTime(2019, 3, 20, 15, 44, 37, 255, DateTimeKind.Local).AddTicks(4591),
                            Fondo = "caja-7",
                            Icono = "poll",
                            Nombre = "Indicadores",
                            Url = "dashboard-indic",
                            Ventana = "indicadores",
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Bandeja Atencion de Solicitudes",
                            Etiqueta = "Atención de Solicitudes",
                            FechaCreacion = new DateTime(2019, 3, 20, 15, 44, 37, 261, DateTimeKind.Local).AddTicks(2378),
                            Fondo = "caja-11",
                            Icono = "description",
                            Nombre = "Atencion de Solicitudes",
                            Url = "bandeja",
                            Ventana = "bandeja",
                            Visible = true
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Administracion",
                            Etiqueta = "Administración",
                            FechaCreacion = new DateTime(2019, 3, 20, 15, 44, 37, 261, DateTimeKind.Local).AddTicks(2472),
                            Fondo = "caja-12",
                            Icono = "supervised_user_circle",
                            Nombre = "Administracion",
                            Url = "bandeja3",
                            Ventana = "administracion",
                            Visible = true
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Atencion al cliente",
                            Etiqueta = "Atención al Cliente",
                            FechaCreacion = new DateTime(2019, 3, 20, 15, 44, 37, 261, DateTimeKind.Local).AddTicks(2481),
                            Fondo = "caja-5",
                            Icono = "contact_phone",
                            Nombre = "Atencion al Cliente",
                            Url = "en-construccion",
                            Ventana = "atencionCliente",
                            Visible = true
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Caja Mayor",
                            Etiqueta = "Caja Mayor",
                            FechaCreacion = new DateTime(2019, 3, 20, 15, 44, 37, 261, DateTimeKind.Local).AddTicks(2489),
                            Fondo = "caja-2",
                            Icono = "money",
                            Nombre = "Caja Mayor",
                            Url = "en-construccion",
                            Ventana = "cajaMayor",
                            Visible = true
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Girasoles",
                            Etiqueta = "Girasoles",
                            FechaCreacion = new DateTime(2019, 3, 20, 15, 44, 37, 261, DateTimeKind.Local).AddTicks(2498),
                            Fondo = "caja-3",
                            Icono = "icon-girasoles",
                            Nombre = "Girasoles",
                            Url = "en-construccion",
                            Ventana = "girasoles",
                            Visible = true
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Control de Cajas",
                            Etiqueta = "Control de Cajas",
                            FechaCreacion = new DateTime(2019, 3, 20, 15, 44, 37, 261, DateTimeKind.Local).AddTicks(2507),
                            Fondo = "caja-4",
                            Icono = "playlist_add_check",
                            Nombre = "Control de Cajas",
                            Url = "en-construccion",
                            Ventana = "controlCaas",
                            Visible = true
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Gestion de Materiales",
                            Etiqueta = "Gestión de Materiales",
                            FechaCreacion = new DateTime(2019, 3, 20, 15, 44, 37, 261, DateTimeKind.Local).AddTicks(2515),
                            Fondo = "caja-6",
                            Icono = "build",
                            Nombre = "Gestion de Materiales",
                            Url = "en-construccion",
                            Ventana = "gestionMateriales",
                            Visible = true
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Auditorias",
                            Etiqueta = "Auditorías",
                            FechaCreacion = new DateTime(2019, 3, 20, 15, 44, 37, 261, DateTimeKind.Local).AddTicks(2519),
                            Fondo = "caja-8",
                            Icono = "search",
                            Nombre = "Auditorias",
                            Url = "en-construccion",
                            Ventana = "auditorias",
                            Visible = true
                        });
                });

            modelBuilder.Entity("Proyecto.Core.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Clasificacion");

                    b.Property<double>("Costo");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Documentacion");

                    b.Property<int>("Duracion");

                    b.Property<bool>("EnBandeja");

                    b.Property<bool>("EsInicial");

                    b.Property<string>("Estado");

                    b.Property<string>("Icono");

                    b.Property<string>("Implementacion");

                    b.Property<int>("ModuloId");

                    b.Property<string>("Nombre");

                    b.Property<int>("Prioridad");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("tareas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Costo = 0.0,
                            Descripcion = "cargar datos",
                            Duracion = 300,
                            EnBandeja = false,
                            EsInicial = true,
                            Icono = "edit",
                            ModuloId = 1,
                            Nombre = "Cargar Datos",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 2,
                            Costo = 0.0,
                            Descripcion = "Autorizacion",
                            Duracion = 120,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-invertir",
                            ModuloId = 1,
                            Nombre = "Autorizar Registro",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 3,
                            Costo = 0.0,
                            Descripcion = "Solicitar Retiro",
                            Duracion = 2,
                            EnBandeja = false,
                            EsInicial = true,
                            Icono = "icon-punto-de-venta",
                            ModuloId = 1,
                            Nombre = "Solicitar Retiro",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 4,
                            Costo = 0.0,
                            Descripcion = "Autorizar Retiro",
                            Duracion = 8,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-adicionales",
                            ModuloId = 2,
                            Nombre = "Autorizar Retiro",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 5,
                            Costo = 0.0,
                            Descripcion = "Autorizar Retiro",
                            Duracion = 8,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-adicionales",
                            ModuloId = 2,
                            Nombre = "Solicitar Tarjeta",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 6,
                            Costo = 0.0,
                            Descripcion = "Autorizar Retiro",
                            Duracion = 8,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-adicionales",
                            ModuloId = 1,
                            Nombre = "Prestamo",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 7,
                            Costo = 0.0,
                            Descripcion = "Autorizar Retiro",
                            Duracion = 8,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-adicionales",
                            ModuloId = 2,
                            Nombre = "Debito Automatico",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 8,
                            Costo = 0.0,
                            Descripcion = "Autorizar Retiro",
                            Duracion = 8,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-adicionales",
                            ModuloId = 1,
                            Nombre = "Actualizar Datos",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 9,
                            Costo = 0.0,
                            Descripcion = "Autorizar Retiro",
                            Duracion = 8,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-adicionales",
                            ModuloId = 2,
                            Nombre = "Activar Cuenta",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 10,
                            Costo = 0.0,
                            Descripcion = "Autorizar Retiro",
                            Duracion = 8,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-adicionales",
                            ModuloId = 1,
                            Nombre = "Actualizar Adicionales",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 11,
                            Costo = 0.0,
                            Descripcion = "Autorizar Retiro",
                            Duracion = 8,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-adicionales",
                            ModuloId = 1,
                            Nombre = "Aumentar Linea",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 12,
                            Costo = 0.0,
                            Descripcion = "Autorizar Retiro",
                            Duracion = 8,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-adicionales",
                            ModuloId = 2,
                            Nombre = "Cambiar Cierre",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 13,
                            Costo = 0.0,
                            Descripcion = "Autorizar Retiro",
                            Duracion = 8,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-adicionales",
                            ModuloId = 1,
                            Nombre = "Enviar EDC",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 14,
                            Costo = 0.0,
                            Descripcion = "Autorizar Retiro",
                            Duracion = 8,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-adicionales",
                            ModuloId = 2,
                            Nombre = "Registros Fallidos",
                            Prioridad = 1
                        },
                        new
                        {
                            Id = 15,
                            Costo = 0.0,
                            Descripcion = "Autorizar Retiro",
                            Duracion = 8,
                            EnBandeja = true,
                            EsInicial = false,
                            Icono = "icon-adicionales",
                            ModuloId = 2,
                            Nombre = "Actualizar Datos Automatico",
                            Prioridad = 1
                        });
                });

            modelBuilder.Entity("Proyecto.Core.Models.Tarea", b =>
                {
                    b.HasOne("Proyecto.Core.Models.Modulo", "Modulo")
                        .WithMany("Tareas")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
